import 'package:agri_farmers_app/MyColors.dart';
import 'package:agri_farmers_app/ReusableWidget.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class PrivacyPolicyPage extends StatelessWidget {
  PrivacyPolicyPage({Key? key}) : super(key: key);
  ReusableWidget reusableWidget = ReusableWidget();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 0,
        backgroundColor: MyColors.deepGreen,
        leading: IconButton(
          onPressed: () {
            Get.back();
          },
          icon: const Icon(
            Icons.arrow_back_ios_new,
            color: Colors.white,
          ),
        ),
      ),
      body: SingleChildScrollView(
        child: Container(
          padding: const EdgeInsets.all(10),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Privacy Policy',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              reusableWidget.textBoxSpace(),
              const Text(
                'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service '
                'and tells You about Your privacy rights and how the law protects You.'
                'We use Your Personal data to provide and improve the Service. By using the Service, '
                'You agree to the collection and use of information in accordance with this Privacy Policy.',
              ),
              const Text(
                'Interpretation and Definitions',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              const Text(
                'Interpretation',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold),
              ),
              const Text(
                'The words of which the initial letter is capitalized have meanings defined under the following conditions.'
                'The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
              ),
              const Text(
                'Definitions',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold),
              ),
              const Text(
                'Account means a unique account created for You to access our Service or parts of our Service.',
              ),
              const Text(
                'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" '
                'means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority',
              ),
              const Text(
                  'Application refers to Agriculture App, the software program provided by the Company.'),
              const Text('Country refers to: Mizoram, India'),
              const Text(
                  'Personal Data is any information that relates to an identified or identifiable individual.'),
              const Text('Service refers to the Application.'),
              const Text(
                  'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'),
              const Text(
                'Collecting and Using Your Personal Data',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              const Text(
                'Types of Data Collected',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold),
              ),
              const Text(
                'Personal Data',
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
              ),
              const Text(
                'While using Our Service, We may ask You to provide Us with certain personally '
                'identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:',
              ),
              const Text('Phone number'
                  ','
                  'Address, State, Province, ZIP/Postal code, City'
                  ','
                  'Usage Data'),
              const Text(
                'Usage Data',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold),
              ),
              const Text(
                  'Usage Data is collected automatically when using the Service.'),
              const Text(
                'Usage Data may include information such as Your Devices'
                ' Internet Protocol address (e.g. IP address), browser type, browser version,'
                ' the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.',
              ),
              const Text(
                'Use of Your Personal Data',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold),
              ),
              const Text(
                'To provide and maintain our Service, including to monitor the usage of our Service.',
              ),
              const Text(
                'To manage Your Account: to manage Your registration as a user of the Service.'
                ' The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.',
              ),
              const Text(
                'For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.',
              ),
              const Text(
                'To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile applications'
                ' push notifications regarding updates or informative communications related to the functionalities, products or contracted services, '
                'including the security updates, when necessary or reasonable for their implementation.',
              ),
              const Text(
                'For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.',
              ),
            ],
          ),
        ),
      ),
    );
  }
}
